on: [push, pull_request]

name: CI for 'libnix' library

jobs:

  build:
    name: Build the package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc:
          - '8.10.1'
          - '8.8.1'
          - '8.6.3'

        aeson: ['-any']
        megaparsec: ['-any']
        prettyprinter: ['-any']
        profunctors: ['-any']

        include:
          - ghc: '8.10.1'
            aeson: '== 1.5.*'

    steps:
      - uses: actions/checkout@v2

      - name: Cache Haskell dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Build
        run: >
            cabal build
            --constraint='aeson ${{matrix.aeson}}'
